### ISSUE TITLE
添加授权后无法查看文件, 无法挂载盘符

### ISSUE THREAD

**Issue by hhuimie** [trueai-org/mdrive#13]
如题, 不知道什么问题, win10系统, 也已安装驱动
![image](https://github.com/trueai-org/mdrive/assets/4830177/8c0cc835-4dfc-4dcc-bca5-3e985c0263ca)
![image](https://github.com/trueai-org/mdrive/assets/4830177/cdea5d8e-e1c0-4d26-9172-f8f3cc3aeadf)

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/2cdf7263-e3b9-4e95-855f-bf5d8d9ae9ca)
经测试，并未重新此问题。
可以尝试一下方案：
1、点击【立即挂载】，更换盘符或设定云盘目录
2、换个账号或换台电脑测试

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/a95d9350-dd0b-4d1c-8d1a-b64c2a5f0c59)
经测试，暂时没有问题，可以启动后查看当前目录的 logs 下的日志文件。

**Comment by hhuimie** [comment]
换了账号, 换了电脑, 也关掉杀毒软件, 都不行, 都是win10, 已安装x64驱动
而且网页无法显示任何数据
![image](https://github.com/trueai-org/mdrive/assets/4830177/396e10bb-fd92-46f9-91e6-57af1c549493)

完整的log如下, 显示是dokan问题, 但是已经安装了
```
[11:11:06 INF] 开始例行检查
[11:11:06 INF] 例行检查完成
[11:12:06 INF] 开始例行检查
[11:12:06 INF] 云盘挂载初始化中
[11:12:08 INF] 云盘挂载初始化完成
[11:12:08 ERR] 执行例行检查时发生异常
System.DllNotFoundException: Dll was not found.
   at DokanNet.Native.NativeMethods.DokanInit()
   at DokanNet.Dokan..ctor(ILogger logger)
   at MDriveSync.Core.Services.AliyunDriveMounter.Mount()
   at MDriveSync.Core.TimedHostedService.DoWork(Object state)
[11:12:25 INF] 云盘挂载初始化中
[11:12:27 INF] 云盘挂载初始化完成
[11:12:27 ERR] 系统异常 Dll was not found.
System.DllNotFoundException: Dll was not found.
   at DokanNet.Native.NativeMethods.DokanInit()
   at DokanNet.Dokan..ctor(ILogger logger)
   at MDriveSync.Core.Services.AliyunDriveMounter.Mount()
   at MDriveSync.Core.TimedHostedService.DriveMount(String driveId)
   at lambda_method68(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by trueai-org** [comment]
1、dokan 安装后，如果加载 dokan 失败，可以重启下电脑试下。
2、网页没有加载列表，是因为没有作业，只有点击作业才能查看对应作业的文件。
![image](https://github.com/trueai-org/mdrive/assets/37255565/87a681d9-e293-483b-a799-24d7439c5a55)

**Comment by hhuimie** [comment]
重启多次了都不行, 都是这个错误
但是[clouddrive](https://www.clouddrive2.com/)就可以

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/f13f1032-e76e-4976-b0b1-0dfb0af55516)
cloud 应该是不同的实现，这个项目依赖了dokan，你可以查看下安装后， dokan 在本地是否存在。
C:\Program Files\Dokan\Dokan Library-<version>

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/c8dedfef-97db-4757-bf6a-adc8fd296151)


如果确认 dokan 目录和 dll 存在，则查看环境变量是否存在，尝试方式：重新安装、修复，或安装 32 位尝试。

Dokan 库未正确安装：确保 Dokan_x64.msi 安装包已正确安装，且所有必要的文件都已放置在适当的位置。你可以检查安装目录，确认 Dokan 的 DLL 文件（如 dokan1.dll）是否存在。

环境变量问题：有时候，系统可能没有正确设置环境变量以包含 DLL 文件的路径。你可以添加包含 Dokan DLL 的目录到你的系统环境变量 PATH 中。这可以通过“控制面板” -> “系统” -> “高级系统设置” -> “环境变量”来完成。

依赖问题：Dokan 依赖于一些系统组件，比如 Microsoft Visual C++ 可再发行组件包。确认你的系统已安装了 Dokan 需要的所有依赖。

系统架构不匹配：确认你安装的 Dokan 版本与你的系统架构（32位或64位）相匹配。如果你的系统是 64 位，确保安装了 Dokan_x64.msi。

重新安装 Dokan：有时候，重新安装 Dokan 可以解决问题。卸载当前安装的 Dokan，然后重新启动你的计算机，再次安装 Dokan_x64.msi。

**Comment by hhuimie** [comment]
谢谢您的耐心解答, 确实是dokan安装的问题, 之前一直是按照失败的, 按照下面的做法成功了
```
1. 删除注册表HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\dokan2
2. 删除C:\Windows\System32\drivers\dokan2.sys
3. 重启安装exe
```
