### ISSUE TITLE
初始化文件列表异常

### ISSUE THREAD

**Issue by cool-chill** [trueai-org/mdrive#21]
```
[21:24:50 INF] 开始例行检查
[21:24:50 INF] 开始例行检查
[21:24:50 INF] 例行检查完成
[21:24:50 INF] 例行检查完成
[21:25:07 INF] 真实大小 0
[21:25:07 INF] 真实大小 0
[21:25:25 INF] 云盘文件加载完成，用时 48604 ms，总文件数：22160
[21:25:25 ERR] 初始化文件列表异常
System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveSearchFiles(Int32 limit)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveInitFiles()

```

**Comment by cool-chill** [comment]
```
[22:23:56 INF] 开始例行检查
[22:23:56 INF] 开始例行检查
[22:23:56 INF] 例行检查完成
[22:23:56 INF] 作业初始化中
[22:23:56 INF] Linux: False, macOS: False, Windows: True
[22:24:56 INF] 开始例行检查
[22:24:56 INF] 例行检查完成
[22:25:06 ERR] 执行例行检查时发生异常
System.Net.Http.HttpRequestException: Received an invalid status line: 'HTTP/1.1 0 '.
   at MDriveSync.Core.Services.ProviderApiHelper.RefreshToken(String refreshToken)
   at MDriveSync.Core.Services.AliyunDriveToken.<>c__DisplayClass2_0.<GetAccessToken>b__0(ICacheEntry c)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at MDriveSync.Core.Services.AliyunDriveToken.GetAccessToken(String id)
   at MDriveSync.Core.AliyunJob.get_AccessToken()
   at MDriveSync.Core.AliyunJob.AliyunDriveInitInfo()
   at MDriveSync.Core.AliyunJob.<AliyunDriveInitialize>b__76_0()
   at MDriveSync.Core.Services.LocalLock.TryLock(String resource, TimeSpan expirationTime, Action action)
   at MDriveSync.Core.AliyunJob.AliyunDriveInitialize()
   at MDriveSync.Core.AliyunJob.StartJob()
   at MDriveSync.Core.AliyunJob.Maintenance()
   at MDriveSync.Core.AliyunDriveHostedService.DoWork(Object state)
[22:25:56 INF] 开始例行检查
[22:25:56 INF] 开始例行检查
[22:25:56 INF] 作业初始化中
[22:25:56 INF] Linux: False, macOS: False, Windows: True
[22:25:56 INF] 例行检查完成
[22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"22e8f697-6bff-4058-904e-f735bd813674","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"c2f37ea7-d603-496b-b86c-3fe7f154db70","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"f6e7fcd7-c355-48d9-879f-ad93efc9b2b8","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 系统异常 Request failed with status code Forbidden
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
   at MDriveSync.Core.Services.AliyunDriveApi.GetSubFolders(String driveId, String parentFileId, String name, String accessToken)
   at MDriveSync.Core.AliyunJob.AliyunDriveInitBackupPath()
   at MDriveSync.Core.AliyunJob.GetDrivleFiles(String parentId)
   at MDriveSync.Client.API.Controllers.AliyunStorageController.GetDrivleFiles(String jobId, String parentId)
   at lambda_method225(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[22:26:20 ERR] 系统异常 Request failed with status code Forbidden
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
   at MDriveSync.Core.Services.AliyunDriveApi.GetSubFolders(String driveId, String parentFileId, String name, String accessToken)
   at MDriveSync.Core.AliyunJob.AliyunDriveInitBackupPath()
   at MDriveSync.Core.AliyunJob.GetDrivleFiles(String parentId)
   at MDriveSync.Client.API.Controllers.AliyunStorageController.GetDrivleFiles(String jobId, String parentId)
   at lambda_method225(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[22:26:20 ERR] 系统异常 Request failed with status code Forbidden
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
   at MDriveSync.Core.Services.AliyunDriveApi.GetSubFolders(String driveId, String parentFileId, String name, String accessToken)
   at MDriveSync.Core.AliyunJob.AliyunDriveInitBackupPath()
   at MDriveSync.Core.AliyunJob.GetDrivleFiles(String parentId)
   at MDriveSync.Client.API.Controllers.AliyunStorageController.GetDrivleFiles(String jobId, String parentId)
   at lambda_method225(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[22:26:20 INF] 作业初始化完成，用时：24337ms
[22:26:20 INF] 作业启动中
[22:26:20 INF] 作业启动完成，用时：0ms
[22:26:20 ERR] 执行例行检查时发生异常
System.FormatException: Unexpected end of expression.
   at Quartz.ThrowHelper.ThrowFormatException(String message, Exception innerException)
   at Quartz.CronExpression.BuildExpression(String expression)
   at Quartz.CronExpression..ctor(String cronExpression)
   at MDriveSync.Core.QuartzCronScheduler.ScheduleNextRun()
   at MDriveSync.Core.QuartzCronScheduler.Start()
   at MDriveSync.Core.AliyunJob.InitJobScheduling()
   at MDriveSync.Core.AliyunJob.StartJob()
   at MDriveSync.Core.AliyunJob.Maintenance()
   at MDriveSync.Core.AliyunDriveHostedService.DoWork(Object state)
[22:26:56 INF] 开始例行检查
[22:26:56 INF] 开始例行检查
[22:26:56 INF] 例行检查完成
[22:26:56 ERR] 执行例行检查时发生异常
System.FormatException: Unexpected end of expression.
   at Quartz.ThrowHelper.ThrowFormatException(String message, Exception innerException)
   at Quartz.CronExpression.BuildExpression(String expression)
   at Quartz.CronExpression..ctor(String cronExpression)
   at MDriveSync.Core.QuartzCronScheduler.ScheduleNextRun()
   at MDriveSync.Core.QuartzCronScheduler.Start()
   at MDriveSync.Core.AliyunJob.InitJobScheduling()
   at MDriveSync.Core.AliyunJob.Maintenance()
   at MDriveSync.Core.AliyunDriveHostedService.DoWork(Object state)
[22:27:37 INF] 云盘文件加载中，包含 0 个文件，2 个文件夹，restic_backup
[22:27:56 INF] 开始例行检查
[22:27:56 INF] 开始例行检查
[22:27:56 INF] 例行检查完成
[22:27:56 ERR] 执行例行检查时发生异常
System.FormatException: Unexpected end of expression.
   at Quartz.ThrowHelper.ThrowFormatException(String message, Exception innerException)
   at Quartz.CronExpression.BuildExpression(String expression)
   at Quartz.CronExpression..ctor(String cronExpression)
   at MDriveSync.Core.QuartzCronScheduler.ScheduleNextRun()
   at MDriveSync.Core.QuartzCronScheduler.Start()
   at MDriveSync.Core.AliyunJob.InitJobScheduling()
   at MDriveSync.Core.AliyunJob.Maintenance()
   at MDriveSync.Core.AliyunDriveHostedService.DoWork(Object state)

```

**Comment by cool-chill** [comment]
挂载成为磁盘时无法使用，不挂载直接使用同步可以成功运行，但有很多报错

**Comment by cool-chill** [comment]
这是我需要备份的文件夹信息
![image](https://github.com/trueai-org/mdrive/assets/89137316/dcf3caa1-34fe-4c78-98eb-52d0db2217c3)

**Comment by trueai-org** [comment]
感谢您的反馈，我这边查下

**Comment by trueai-org** [comment]
> [22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"22e8f697-6bff-4058-904e-f735bd813674","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"c2f37ea7-d603-496b-b86c-3fe7f154db70","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"f6e7fcd7-c355-48d9-879f-ad93efc9b2b8","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
System.Net.Http.HttpRequestException: Request failed with status code Forbidden
[22:26:20 ERR] 系统异常 Request failed with status code Forbidden

根据这里的错误提示，这里应该是授权错误，建议重新授权试试或者解除授权再次重新授权。

**Comment by cool-chill** [comment]
> > [22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"22e8f697-6bff-4058-904e-f735bd813674","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
> > System.Net.Http.HttpRequestException: Request failed with status code Forbidden
> > [22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"c2f37ea7-d603-496b-b86c-3fe7f154db70","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
> > System.Net.Http.HttpRequestException: Request failed with status code Forbidden
> > [22:26:20 ERR] 请求失败：/adrive/v1.0/openFile/search Forbidden {"code":"UserNotAllowedAccessDrive","message":"user not allowed access drive","data":null,"headers":null,"requestId":"f6e7fcd7-c355-48d9-879f-ad93efc9b2b8","pdsRequestId":null,"resultCode":"UserNotAllowedAccessDrive","display_message":null}
> > System.Net.Http.HttpRequestException: Request failed with status code Forbidden
> > [22:26:20 ERR] 系统异常 Request failed with status code Forbidden
> 
> 根据这里的错误提示，这里应该是授权错误，建议重新授权试试或者解除授权再次重新授权。

这个错误只出现了一次，感觉并不是关键，主要是经常性的出现以下错误
```
[23:24:04 ERR] 执行例行检查时发生异常
System.FormatException: Unexpected end of expression.
   at Quartz.ThrowHelper.ThrowFormatException(String message, Exception innerException)
   at Quartz.CronExpression.BuildExpression(String expression)
   at Quartz.CronExpression..ctor(String cronExpression)
   at MDriveSync.Core.QuartzCronScheduler.ScheduleNextRun()
   at MDriveSync.Core.QuartzCronScheduler.Start()
   at MDriveSync.Core.AliyunJob.InitJobScheduling()
   at MDriveSync.Core.AliyunJob.Maintenance()
   at MDriveSync.Core.AliyunDriveHostedService.DoWork(Object state)

```

**Comment by cool-chill** [comment]
```
System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveSearchFiles(Int32 limit)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveInitFiles()

```
此错误是否是因为 整数溢出

**Comment by trueai-org** [comment]
> [23:24:04 ERR] 执行例行检查时发生异常
这里发生错误，应该是 corn 表达式错误了。

你参考这里看下。
```
// cron 表达式 基于 Quartz 3.8.0
// https://www.bejson.com/othertools/cron/

// 每 5 秒
0/5 * * * * ?

// 每分钟
0 * * * * ?

// 每 5 分钟
0 0/5 * * * ?

// 每 10 分钟
0 0/10 * * * ?

// 每天 9 点
0 0 9 * * ?

// 每天 8 点 10 分
0 10 8 * * ?
```

**Comment by cool-chill** [comment]
> > [23:24:04 ERR] 执行例行检查时发生异常
> > 这里发生错误，应该是 corn 表达式错误了。
> 
> 你参考这里看下。
> 
> ```
> // cron 表达式 基于 Quartz 3.8.0
> // https://www.bejson.com/othertools/cron/
> 
> // 每 5 秒
> 0/5 * * * * ?
> 
> // 每分钟
> 0 * * * * ?
> 
> // 每 5 分钟
> 0 0/5 * * * ?
> 
> // 每 10 分钟
> 0 0/10 * * * ?
> 
> // 每天 9 点
> 0 0 9 * * ?
> 
> // 每天 8 点 10 分
> 0 10 8 * * ?
> ```

是的，我缺少了 ? ，修改后重启问题不再出现

**Comment by cool-chill** [comment]
> ```
> [21:24:50 INF] 开始例行检查
> [21:24:50 INF] 开始例行检查
> [21:24:50 INF] 例行检查完成
> [21:24:50 INF] 例行检查完成
> [21:25:07 INF] 真实大小 0
> [21:25:07 INF] 真实大小 0
> [21:25:25 INF] 云盘文件加载完成，用时 48604 ms，总文件数：22160
> [21:25:25 ERR] 初始化文件列表异常
> System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveSearchFiles(Int32 limit)
>    at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveInitFiles()
> ```

最开始的问题还没有解决

**Comment by trueai-org** [comment]
> System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveSearchFiles(Int32 limit)
   at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveInitFiles()

可以查看下是否云盘这个文件存在多个，因为阿里云盘允许重复文件夹/文件。
或者重新修改备份目录，保存后重启程序，重新执行备份试下。

**Comment by cool-chill** [comment]
> > System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f
> > at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
> > at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveSearchFiles(Int32 limit)
> > at MDriveSync.Core.Services.AliyunDriveMounter.AliyunDriveInitFiles()
> 
> 可以查看下是否云盘这个文件存在多个，因为阿里云盘允许重复文件夹/文件。 或者重新修改备份目录，保存后重启程序，重新执行备份试下。

这里并没有执行备份，只是挂载磁盘，点击立即挂载后，输出初始化获取文件列表就报这个错了，至于文件存在多个我想应该是没有的，我也试了一下，不能创建同名文件夹
![image](https://github.com/trueai-org/mdrive/assets/89137316/29ca6860-f154-42e1-8e7d-211b5a58b5c1)

**Comment by trueai-org** [comment]
你好，经测试，挂载超过 500GB，超过 20000+ 文件目前没有重现此问题。

> 这里并没有执行备份，只是挂载磁盘，点击立即挂载后，输出初始化获取文件列表就报这个错了，至于文件存在多个我想应该是没有的，我也试了一下，不能创建同名文件夹

是的，通过 GUI 是没法创建的同名的。同名创建是指，通过 API 是允许同名的。

建议排查这个目录的文件：
> System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f

**Comment by cool-chill** [comment]
> 你好，经测试，挂载超过 500GB，超过 20000+ 文件目前没有重现此问题。
> 
> > 这里并没有执行备份，只是挂载磁盘，点击立即挂载后，输出初始化获取文件列表就报这个错了，至于文件存在多个我想应该是没有的，我也试了一下，不能创建同名文件夹
> 
> 是的，通过 GUI 是没法创建的同名的。同名创建是指，通过 API 是允许同名的。
> 
> 建议排查这个目录的文件：
> 
> > System.ArgumentException: An item with the same key has already been added. Key: COOLCHILL-PC/restic_backup/data/69/69776173f6c4c40980205462654ec4a5f3b80b1f43dfbb3b13cb370c52ad957f

是的，经过排查，我发现是阿里云盘windows客户端自带的同步功能所导致的问题，他会创建一个windows用户名的文件夹保存备份，关闭后并在android客户端删除那个备份文件夹(windows客户端无法删除)后再挂载一切正常
![image](https://github.com/trueai-org/mdrive/assets/89137316/8ac0a7ee-21e0-4c77-b2e0-10ce90aa81ec)
