### ISSUE TITLE
执行例行检查时发生异常，refreshToken可以正常用，其他脚本用来正常签到能用，这里重复拿了也用不了

### ISSUE THREAD

**Issue by zboku222** [trueai-org/mdrive#6]
[16:31:04 INF] 开始例行检查
[16:31:04 INF] 作业初始化中
[16:31:04 INF] Linux: False
[16:31:06 ERR] 执行例行检查时发生异常
System.Net.Http.HttpRequestException: Request failed with status code Unauthorized
   at MDriveSync.Core.Services.ProviderApiHelper.RefreshToken(String refreshToken)
   at MDriveSync.Core.Job.InitToken()
   at MDriveSync.Core.Job.<get_AccessToken>b__47_0(ICacheEntry c)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at MDriveSync.Core.Job.get_AccessToken()
   at MDriveSync.Core.Job.AliyunDriveInitInfo()
   at MDriveSync.Core.Job.<AliyunDriveInitialize>b__72_0()
   at MDriveSync.Core.Services.LocalLock.TryLock(String resource, TimeSpan expirationTime, Action action)
   at MDriveSync.Core.Job.AliyunDriveInitialize()
   at MDriveSync.Core.Job.Maintenance()
   at MDriveSync.Core.TimedHostedService.DoWork(Object state)

**Comment by trueai-org** [comment]
在阿里云盘授权管理中，每个 APP 的授权都是独立的，因此不能使用其他 APP 授权的 refreshToken，必须使用 MDrive APP 授权才可以的。
![image](https://github.com/trueai-org/MDriveSync/assets/37255565/6d86515c-f37a-44b1-9e34-2cbd73afc626)

**Comment by trueai-org** [comment]
如果是通过网页或开发者工具网页获取的 refreshToken，目前也是不支持的，必须是通过 OPEN API 授权的。
