### ISSUE TITLE
建议考虑是否需要集成Dokan的相关东西

### ISSUE THREAD

**Issue by goldsmith9702** [trueai-org/mdrive#8]
Windows 10 企业版 LTSC，运行时报错如下
```
2024-02-16 00:57:56.519 +08:00 [INF] 开始例行检查
2024-02-16 00:57:56.519 +08:00 [INF] 云盘挂载初始化中
2024-02-16 00:57:58.958 +08:00 [INF] 云盘挂载初始化完成
2024-02-16 00:57:58.958 +08:00 [ERR] 执行例行检查时发生异常
System.DllNotFoundException: Dll was not found.
   at DokanNet.Native.NativeMethods.DokanInit()
   at DokanNet.Dokan..ctor(ILogger logger)
   at MDriveSync.Core.Services.AliyunDriveMounter.Mount()
   at MDriveSync.Core.TimedHostedService.DoWork(Object state)
```

我从 [https://github.com/dokan-dev/dokany](https://github.com/dokan-dev/dokany) 下载安装Dokan后就正常了

**Comment by trueai-org** [comment]
感谢您的建议。
是的，如果挂载到本地磁盘，时需要此插件。在 web UI 挂载时已经说明了，由于本软件是`免安装`版，因此没有集成到包里面。
![image](https://github.com/trueai-org/MDriveSync/assets/37255565/508a14c2-2955-4c45-9ca1-c98bf64811b5)

**Comment by lucaslml0** [comment]
docker 运行也是报错这个

**Comment by trueai-org** [comment]
> docker 运行也是报错这个

此问题已修复。
