### ISSUE TITLE
ubuntu docker 同步失败

### ISSUE THREAD

**Issue by 1368129224** [trueai-org/mdrive#9]
错误日志

```
System.DllNotFoundException: Unable to load shared library 'dokan2.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/runtimes/linux-x64/native/dokan2.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/dokan2.dll.so: cannot open shared object file: No such file or directory
/app/dokan2.dll.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/libdokan2.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libdokan2.dll.so: cannot open shared object file: No such file or directory
/app/libdokan2.dll.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/dokan2.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/dokan2.dll: cannot open shared object file: No such file or directory
/app/dokan2.dll: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/libdokan2.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libdokan2.dll: cannot open shared object file: No such file or directory
/app/libdokan2.dll: cannot open shared object file: No such file or directory
   at DokanNet.Native.NativeMethods.DokanInit()
   at DokanNet.Dokan..ctor(ILogger logger)
   at MDriveSync.Core.Services.AliyunDriveMounter.Mount() in /src/src/MDriveSync.Core/Services/AliyunDriveMounter.cs:line 1276
   at MDriveSync.Core.TimedHostedService.DoWork(Object state) in /src/src/MDriveSync.Core/Services/TimedHostedService.cs:line 114
```

**Comment by trueai-org** [comment]
感谢，正在修复。

**Comment by trueai-org** [comment]
感谢，目前非 windows 系统暂不支持磁盘挂载，计划 3.x 版本计划提供支持。
感谢您提供的建议。
